<?php
// AdBoard Pro Configuration - Generated by installer

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_USER', 'novado');
define('DB_PASS', 'Q05021998');
define('DB_NAME', 'iteiyzke_project');

// Site Configuration
define('SITE_URL', 'https://novado.shop');
define('SITE_NAME', 'AdBoard Pro');
define('SITE_EMAIL', '');
define('SITE_DESCRIPTION', 'Сучасна дошка оголошень');

// Security
define('SECRET_KEY', 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6');
define('JWT_SECRET', 'z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3i2h1g0f9e8d7c6b5a4');
define('SESSION_NAME', 'adboard_session');

// Environment
define('DEBUG_MODE', false);
define('MAINTENANCE_MODE', false);

// Upload settings
define('UPLOAD_PATH', 'uploads/');
define('MAX_FILE_SIZE', 10485760); // 10MB
define('ALLOWED_EXTENSIONS', 'jpg,jpeg,png,gif,webp');

// Pagination
define('ITEMS_PER_PAGE', 12);

// Email settings (can be configured later)
define('SMTP_HOST', '');
define('SMTP_PORT', 587);
define('SMTP_USER', '');
define('SMTP_PASS', '');
define('SMTP_SECURE', 'tls');

// Session settings
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.cookie_secure', 0); // Set to 1 for HTTPS

// Auto-loading
spl_autoload_register(function ($class) {
    $file = __DIR__ . '/classes/' . $class . '.php';
    if (file_exists($file)) {
        require_once $file;
    }
});

// Include core files
require_once __DIR__ . '/database.php';
// functions.php буде включено пізніше для уникнення конфліктів MySQL

// Database connection using Singleton
try {
    $db = Database::getInstance();
    $db->getConnection()->set_charset('utf8mb4');
    
    // Also create global $db variable for backward compatibility
    $GLOBALS['db'] = $db->getConnection();
    
} catch (Exception $e) {
    if (defined('DEBUG_MODE') && DEBUG_MODE) {
        error_log('Database connection error: ' . $e->getMessage());
        die('Database connection error: ' . $e->getMessage());
    } else {
        error_log('Database connection error: ' . $e->getMessage());
        die('Database connection error');
    }
}

// Start session
if (session_status() == PHP_SESSION_NONE) {
    session_name(SESSION_NAME);
    session_start();
}

// Generate CSRF token
if (!isset($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}
?>
